version: '{build}'

pull_requests:
    do_not_increment_build_number: true

nuget:  
    disable_publish_on_pr: true

configuration: Release

install:
    ps: >-
        $assembly_version = & .\build\GetAssemblyVersion.ps1;
        Update-AppveyorBuild -Version "1.0.$($env:APPVEYOR_BUILD_NUMBER).$($env:APPVEYOR_REPO_TAG)";

assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}-{APPVEYOR_REPO_COMMIT}'

before_build:
    # make sure the artifacts output folder is clear and restore NuGet packages before running MSBuild
    ps: >-
        if(Test-Path .\artifacts) { Remove-Item .\artifacts -Force -Recurse } else { mkdir artifacts } 
        nuget restore AppVeyor.Playground.sln -verbosity detailed

build:
    verbosity: minimal
    project: AppVeyor.Playground.sln

after_build:
    nuget pack Appveyor.Playground/AppVeyor.Playground.csproj -Build -Properties Configuration=Release -OutputDirectory .\artifacts -Exclude **\*.config -Verbosity detailed

artifacts:
    path: .\artifacts\**\*.nupkg